### ISSUE TITLE
Scroll to heading doesn't work if heading contains `code`

### ISSUE THREAD

**Issue by igorakkerman** [oin/obsidian-gotoheading#5]
When navigating to a heading that contains a \`code\` element, the editor might not scroll to center it.

Example: 
```markdown
# `function`
scrolling here doesn't work
# `function` keyword
scrolling here works
# keyword `function`
scrolling here doesn't work
# keyword `function` 
(there is a blank behind `function`)
scrolling here doesn't work
```

**Comment by oin** [comment]
The function used to create an editor position range to scroll to (`Editor.wordAt`) wasn't always returning a useful result, probably because of a strict definition of _word_ (when the line ends with a `code` element, it returns `null`). I added a fallback case with an empty range at the current cursor position.

**Comment by igorakkerman** [comment]
Perfect, thanks a lot for fixing it so fast!
